build: false
environment:
  matrix:
    -
      nodejs_version: "0.12"
    -
      nodejs_version: "2.0"
install:
  -
    ps: "Install-Product node $env:nodejs_version"
  - "npm install"
test_script:
  - "node --version"
  - "npm --version"
  - "npm run test:cover"
